import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, ReactNode, useContext, useEffect, useState } from 'react';

export type Language = 'zh-TW' | 'zh-CN' | 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
  resetLanguage: () => Promise<void>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'app_language';

// Translation data
const translations = {
  'zh-TW': {
    // Navigation
    'nav.home': '首頁',
    'nav.mood': '心情',
    'nav.explore': '探索',
    'nav.profile': '我的',
    
    // Profile Screen
    'profile.title': '我的',
    'profile.userJoinedDays': '與 Rebloom 相伴 {{days}} 天',
    'profile.logout': '登出',
    'profile.logoutConfirm': '登出確認',
    'profile.logoutMessage': '您確定要登出嗎？',
    'profile.cancel': '取消',
    'profile.version': 'Rebloom v{{version}}',
    
    // Profile Sections
    'profile.section.personal': '個人資料',
    'profile.section.subscription': '訂閱與付費',
    'profile.section.ai': 'AI 設定',
    'profile.section.notifications': '通知與提醒',
    'profile.section.privacy': '隱私與安全',
    'profile.section.support': '支持與幫助',
    'profile.section.about': '關於',
    
    // Profile Items
    'profile.personalInfo': '個人信息',
    'profile.personalInfo.subtitle': '編輯您的個人資料和偏好',
    'profile.avatar': '頭像設置',
    'profile.avatar.subtitle': '更換您的個人頭像',
    'profile.subscription': '我的訂閱',
    'profile.subscription.subtitle': '管理您的訂閱計劃',
    'profile.billing': '帳單記錄',
    'profile.billing.subtitle': '查看付費記錄和發票',
    'profile.aiPersonality': 'AI 個性設置',
    'profile.aiPersonality.subtitle': '調整AI伴侶的個性特質和技術特性',
    
    // AI Settings
    'ai.personalizeTitle': '個性化您的AI伴侶',
    'ai.personalizeDescription': '調整AI的個性特質、語音風格和技術特性，打造專屬於您的心理健康伴侶。',
    'ai.personality': 'AI個性類型',
    'ai.voiceSettings': '語音設置',
    'ai.voiceType': '語音類型',
    'ai.personalityTraits': '個性特質調節',
    'ai.empathyLevel': '同理心程度',
    'ai.directnessLevel': '直接程度',
    'ai.humorLevel': '幽默感',
    'ai.formalityLevel': '正式程度',
    'ai.modelSettings': 'AI模型設置',
    'ai.languageModel': '語言模型',
    'ai.advancedFeatures': '進階功能',
    'ai.proactiveSupport': '主動支持',
    'ai.proactiveSupport.description': 'AI會主動關心您的狀態並提供支持',
    'ai.smartSuggestions': '智能建議',
    'ai.smartSuggestions.description': '基於對話內容提供個性化建議',
    'ai.learningMode': '學習模式',
    'ai.learningMode.description': 'AI會記住您的偏好並持續改進',
    'ai.voiceEnabled': '語音對話',
    'ai.voiceEnabled.description': '啟用語音輸入和AI語音回應功能',
    'ai.crisisDetection': '危機檢測',
    'ai.crisisDetection.description': '自動檢測心理危機並提供適當資源',
    'profile.therapeuticApproach': '治療方法偏好',
    'profile.therapeuticApproach.subtitle': '選擇您偏好的治療取向',
    'profile.conversationStyle': '對話風格',
    'profile.conversationStyle.subtitle': '設置對話的深度和頻率',
    'profile.notifications': '推送通知',
    'profile.notifications.subtitle': '管理通知和提醒設置',
    'profile.moodReminders': '心情記錄提醒',
    'profile.moodReminders.subtitle': '設置心情追蹤提醒時間',
    'profile.wellnessCheck': '健康檢查提醒',
    'profile.wellnessCheck.subtitle': '定期心理健康檢查提醒',
    'profile.privacySettings': '隱私設置',
    'profile.privacySettings.subtitle': '控制數據分享和存儲',
    'profile.dataExport': '數據導出',
    'profile.dataExport.subtitle': '下載您的對話記錄',
    'profile.emergencyContacts': '緊急聯絡人',
    'profile.emergencyContacts.subtitle': '設置緊急情況聯絡人',
    'profile.crisisResources': '危機資源',
    'profile.crisisResources.subtitle': '緊急心理健康資源',
    'profile.helpCenter': '幫助中心',
    'profile.helpCenter.subtitle': '常見問題和使用指南',
    'profile.contactSupport': '聯絡客服',
    'profile.contactSupport.subtitle': '獲得技術支持和幫助',
    'profile.feedback': '意見反饋',
    'profile.feedback.subtitle': '幫助我們改進應用',
    'profile.about': '關於 Rebloom',
    'profile.about.subtitle': '應用版本和信息',
    'profile.terms': '服務條款',
    'profile.terms.subtitle': '使用條款和政策',
    'profile.privacyPolicy': '隱私政策',
    'profile.privacyPolicy.subtitle': '了解我們如何保護您的隱私',
    'profile.languageSettings': '語言設置',
    'profile.languageSettings.subtitle': '選擇應用顯示語言',
    
    // Language Settings
    'language.title': '語言設置',
    'language.select': '選擇語言',
    'language.zh-TW': '繁體中文',
    'language.zh-CN': '簡體中文',
    'language.ja': '日本語',
    'language.en': 'English',
    'language.save': '保存',
    'language.saveSuccess': '語言設置已保存',
    
    // Home Screen / Chat
    'home.greeting': '嗨！👋\n\n我是 Ash，您的AI心理健康伴侶。我在這裡傾聽、理解，並幫助您處理心中的想法。\n\n您今天感覺如何？',
    'home.aiResponses.1': '我聽到了，我希望您知道您的感受完全有效。您能告訴我更多關於您心中想法的事嗎？',
    'home.aiResponses.2': '謝謝您與我分享這些。敞開心扉談論這些感受需要勇氣。您經歷這種感覺多久了？',
    'home.aiResponses.3': '我在這裡傾聽並支持您度過這個困難時期。現在什麼對您最有幫助？',
    'home.aiResponses.4': '這聽起來真的很有挑戰性。您並不孤單，很高興您尋求支持。',
    'home.aiResponses.5': '我很感謝您信任我。讓我們一起解決這個問題。您認為現在什麼能讓您感覺好一點？',
    
    // Mood Screen
    'mood.title': '心情日記',
    'mood.subtitle': '追蹤您的情感旅程',
    'mood.thisWeek': '本週',
    'mood.averageMood': '平均心情',
    'mood.daysTracked': '已追蹤天數',
    'mood.insights': '洞察',
    'mood.moodThisWeek': '本週心情',
    'mood.weeklyPatterns': '週間模式',
    'mood.moodImproves': '您的心情在週末會改善',
    'mood.highConfidence': '高置信度',
    'mood.weekendPattern': '您在週六和週日往往感覺更積極。這表明休息和放鬆對您的健康很重要。',
    'mood.7days': '7天',
    'mood.30days': '30天',
    'mood.3months': '3個月',
    'mood.low': '低',
    'mood.neutral': '中性',
    'mood.high': '高',
    'mood.goodDay': '好日子',
    'mood.toughDay': '艱難的一天',
    'mood.todaysInsights': '今日洞察',
    'mood.insightsFor': '{{date}}的洞察',
    'mood.noConversations': '這一天沒有對話',
    'mood.noConversationsText': '選擇有對話的日期來查看您的每日洞察和心理支持。',
    'mood.startConversation': '開始對話',
    
    // Daily Insight Card
    'insight.sessions': '次對話',
    'insight.todaysAffirmation': '今日肯定',
    'insight.tomorrowsFocus': '明日重點',
    'insight.emotionalJourney': '情感歷程',
    'insight.positiveReframe': '正向重構',
    'insight.actionStep': '行動步驟',
    'insight.conversationAnalysis': '對話分析',
    'insight.messagesShared': '您今天分享了 {{count}} 條訊息',
    'insight.emotionalFlow': '情感流動',
    'insight.breakthroughs': '✨ 突破',
    'insight.areasToWatch': '⚠️ 需要關注的地方',
    'insight.saveInsight': '保存洞察',
    'insight.shareProgress': '分享進度',
    
    // Explore/Progress Screen
    'explore.title': '您的進度',
    'explore.thisWeek': '本週',
    'explore.averageMood': '平均心情',
    'explore.daysTracked': '已追蹤天數',
    'explore.insights': '洞察',
    'explore.weeklyPatterns': '週間模式',
    'explore.yourGoals': '您的目標',
    'explore.dailyMoodCheckins': '每日心情記錄',
    'explore.mindfulnessPractice': '正念練習',
    'explore.daysProgress': '{{current}}/{{total}} 天',
    'explore.moodTrackingSuccess': '您成功地每天追蹤心情一整週！🎉',
    'explore.mindfulnessProgress': '繼續努力！您正在建立一個很好的習慣。',
    'explore.7days': '7天',
    'explore.30days': '30天',
    'explore.3months': '3個月',
    
    // Weekly Insights
    'weeklyInsight.moodImproves': '您的心情在週末會改善',
    'weeklyInsight.moodImprovesDesc': '您在週六和週日往往感覺更積極。這表明休息和放鬆對您的健康很重要。',
    'weeklyInsight.consistentImprovement': '本週持續改善',
    'weeklyInsight.consistentImprovementDesc': '您的整體心情在過去7天中呈上升趨勢。繼續保持！',
    'weeklyInsight.checkinsCompleted': '完成7天記錄',
    'weeklyInsight.checkinsCompletedDesc': '恭喜！您連續一週都追蹤了心情。這種自我覺察是心理健康旅程中的關鍵步驟。',
    'weeklyInsight.veryHighConfidence': '極高置信度',
    'weeklyInsight.highConfidence': '高置信度',
    'weeklyInsight.mediumConfidence': '中等置信度',
    'weeklyInsight.lowConfidence': '低置信度',
    
    // Daily Insight Examples
    'insightExample.1.summary': '今天展現了非凡的情感韌性。儘管面臨挑戰，您保持了積極的態度並主動尋求解決方案。',
    'insightExample.1.support': '您比自己想像的更強大。您今天面對的每一個挑戰都證明了您驚人的韌性。您有能力克服生活中的任何困難。💪✨',
    'insightExample.1.recommendation': '繼續練習今天有效的接地技巧。考慮在睡前記錄您的成就。',
    'insightExample.1.pattern': '從焦慮開始，經歷決心，最終以平靜的信心結束',
    'insightExample.1.reframe': '感覺像是障礙的事物實際上是成長的機會。您將挑戰轉化為墊腳石。',
    'insightExample.1.action': '明天早上，提醒自己：「我有能力處理任何困難。」',
    'insightExample.1.topics.0': '韌性',
    'insightExample.1.topics.1': '解決問題',
    'insightExample.1.topics.2': '自我關懷',
    'insightExample.1.emotions.0': '焦慮',
    'insightExample.1.emotions.1': '堅定',
    'insightExample.1.emotions.2': '自信',
    'insightExample.1.emotions.3': '感恩',
    'insightExample.1.breakthroughs.0': '將焦慮視為信息，而非指令',
    'insightExample.1.breakthroughs.1': '在壓力時刻成功使用呼吸技巧',
    'insightExample.1.breakthroughs.2': '在困難對話中清楚表達需求',
    
    'insightExample.2.summary': '情緒複雜的一天，但您通過尋求幫助和建設性地處理情感展現了驚人的自我覺察。',
    'insightExample.2.support': '您願意表現脆弱並尋求支持展現了巨大的勇氣。您被愛著、被重視著，值得擁有所有美好的事物。🌟❤️',
    'insightExample.2.recommendation': '練習我們討論的自我照顧例行公事。記住要像對待親愛的朋友一樣善待自己。',
    'insightExample.2.pattern': '一整天在悲傷和希望之間波動',
    'insightExample.2.reframe': '您的情感起伏是您人性和深度的體現。這不是弱點——這是真實的生活。',
    'insightExample.2.action': '創建一個「善待自己」清單，列出5種您可以對自己表現同情的具體方式。',
    'insightExample.2.topics.0': '自我覺察',
    'insightExample.2.topics.1': '情感處理',
    'insightExample.2.topics.2': '尋求支持',
    'insightExample.2.emotions.0': '憂鬱',
    'insightExample.2.emotions.1': '不知所措',
    'insightExample.2.emotions.2': '充滿希望',
    'insightExample.2.emotions.3': '平靜',
    'insightExample.2.breakthroughs.0': '無評判地識別觸發因素',
    'insightExample.2.breakthroughs.1': '感到不知所措時尋求幫助',
    'insightExample.2.breakthroughs.2': '在困難情緒中練習正念呼吸',
    'insightExample.2.concerns.0': '早上自我批評的內心對話',
    'insightExample.2.concerns.1': '傾向於貶低成就',
    
    'insightExample.3.summary': '情感平衡和生產力的絕佳一天。您展現了強大的情商和自我照顧實踐。',
    'insightExample.3.support': '您是光明和力量的燈塔。今天您向世界——也向自己——展示了您是多麼有能力和美好。繼續發光！✨🌈',
    'insightExample.3.recommendation': '通過保持今天有效的例行公事來延續今天的成功。考慮與他人分享您的正能量。',
    'insightExample.3.pattern': '穩定的正能量，伴隨著真正的快樂和滿足時刻',
    'insightExample.3.reframe': '您通過自己的選擇和態度創造了美好的一天。當您信任自己時，這就是您的自然狀態。',
    'insightExample.3.action': '寫下今天特別的地方，這樣您就可以再次創造這些條件。',
    'insightExample.3.topics.0': '平衡',
    'insightExample.3.topics.1': '生產力',
    'insightExample.3.topics.2': '快樂',
    'insightExample.3.emotions.0': '充滿活力',
    'insightExample.3.emotions.1': '滿足',
    'insightExample.3.emotions.2': '快樂',
    'insightExample.3.breakthroughs.0': '儘管面臨意外挑戰仍保持積極心態',
    'insightExample.3.breakthroughs.1': '成功平衡工作與自我照顧',
    'insightExample.3.breakthroughs.2': '與所愛的人有意義地連結',
    
    // Case Study: Chinese International Student (Monday-Saturday)
    'caseStudy.student.name': '小明 (化名)',
    'caseStudy.student.profile': '高二中國留學生，16歲，在美國求學3個月',
    
    // Monday - Crisis Day
    'caseStudy.monday.summary': '今天經歷了嚴重的情感危機。在學校食堂被同學嘲笑英語發音，感到深度羞恥和孤立。語言障礙造成的挫敗感達到頂峰。',
    'caseStudy.monday.support': '你的感受完全可以理解，小明。適應新文化和語言是極其困難的過程，你已經展現了巨大的勇氣。每一個在異國他鄉求學的人都會經歷這樣的挑戰。你並不孤單，這些困難是暫時的。💪🌟',
    'caseStudy.monday.recommendation': '明天嘗試與學校的國際學生顧問預約談話。今晚練習深呼吸技巧，寫下三件你今天做得好的事情，無論多小。',
    'caseStudy.monday.pattern': '從早上的緊張不安，到中午的羞恥感爆發，晚上陷入深度自我懷疑',
    'caseStudy.monday.reframe': '被嘲笑反映的是他人的無知，而不是你的價值。你的勇氣在於每天都在嘗試用第二語言溝通，這是值得讚賞的成就。',
    'caseStudy.monday.action': '明天上學前，對鏡子說：「我正在學習，每一次嘗試都讓我更強大。」',
    'caseStudy.monday.topics.0': '語言障礙',
    'caseStudy.monday.topics.1': '校園霸凌',
    'caseStudy.monday.topics.2': '文化適應',
    'caseStudy.monday.emotions.0': '緊張',
    'caseStudy.monday.emotions.1': '羞恥',
    'caseStudy.monday.emotions.2': '孤立',
    'caseStudy.monday.emotions.3': '絕望',
    'caseStudy.monday.breakthroughs.0': '勇敢地向治療師分享了真實感受',
    'caseStudy.monday.breakthroughs.1': '認識到語言學習需要時間和耐心',
    'caseStudy.monday.concerns.0': '嚴重的自我價值感低落',
    'caseStudy.monday.concerns.1': '社交迴避行為加劇',
    
    // Tuesday - Seeking Help
    'caseStudy.tuesday.summary': '按照建議與國際學生顧問會面。雖然仍感焦慮，但開始尋求學校資源的幫助。第一次感受到被理解和支持。',
    'caseStudy.tuesday.support': '你邁出了最重要的一步！尋求幫助需要巨大的勇氣，這顯示了你的智慧和成熟。你正在建立支持網絡，這是康復過程中的關鍵步驟。繼續相信自己！🌈✨',
    'caseStudy.tuesday.recommendation': '參加學校的英語會話小組。與顧問討論的應對策略要持續練習。今晚給家人打電話，分享你的感受。',
    'caseStudy.tuesday.pattern': '早上帶著忐忑不安的心情，中午感到被理解，晚上出現希望的曙光',
    'caseStudy.tuesday.reframe': '尋求幫助不是軟弱的表現，而是智慧和自我關愛的體現。你正在積極地為自己的福祉負責。',
    'caseStudy.tuesday.action': '每天至少與一個人進行英語對話，即使只是簡單的問候。',
    'caseStudy.tuesday.topics.0': '尋求幫助',
    'caseStudy.tuesday.topics.1': '建立支持系統',
    'caseStudy.tuesday.topics.2': '自我倡導',
    'caseStudy.tuesday.emotions.0': '忐忑',
    'caseStudy.tuesday.emotions.1': '被理解',
    'caseStudy.tuesday.emotions.2': '希望',
    'caseStudy.tuesday.emotions.3': '感激',
    'caseStudy.tuesday.breakthroughs.0': '成功與學校顧問建立聯繫',
    'caseStudy.tuesday.breakthroughs.1': '學會了三個應對焦慮的技巧',
    'caseStudy.tuesday.breakthroughs.2': '意識到自己並非唯一面臨這些挑戰的學生',
    
    // Wednesday - Small Victory
    'caseStudy.wednesday.summary': '參加了英語會話小組，雖然緊張但成功完成了自我介紹。遇到了另一位亞裔同學，感到不再那麼孤單。',
    'caseStudy.wednesday.support': '這是一個重大的勝利！你克服了恐懼，勇敢地參與了小組活動。找到同伴是治癒過程中的重要里程碑。你的勇氣正在為你打開新的機會之門。🎉💝',
    'caseStudy.wednesday.recommendation': '與新認識的同學保持聯繫，考慮一起學習或用餐。繼續參加會話小組，逐漸建立信心。',
    'caseStudy.wednesday.pattern': '初始緊張，逐漸放鬆，最終感到歸屬感和連結',
    'caseStudy.wednesday.reframe': '你的緊張是正常的，但你選擇了行動而非迴避。這種勇氣將成為你未來成功的基石。',
    'caseStudy.wednesday.action': '明天主動向新朋友打招呼，提議一起吃午餐。',
    'caseStudy.wednesday.topics.0': '社交突破',
    'caseStudy.wednesday.topics.1': '建立友誼',
    'caseStudy.wednesday.topics.2': '克服恐懼',
    'caseStudy.wednesday.emotions.0': '緊張',
    'caseStudy.wednesday.emotions.1': '勇敢',
    'caseStudy.wednesday.emotions.2': '連結',
    'caseStudy.wednesday.emotions.3': '希望',
    'caseStudy.wednesday.breakthroughs.0': '成功在小組中自我介紹',
    'caseStudy.wednesday.breakthroughs.1': '建立了第一個潛在友誼',
    'caseStudy.wednesday.breakthroughs.2': '發現其他學生也有類似困擾',
    
    // Thursday - Building Confidence  
    'caseStudy.thursday.summary': '與新朋友李華一起吃午餐，分享了彼此的留學經歷。在數學課上主動回答問題，獲得老師讚賞。自信心開始恢復。',
    'caseStudy.thursday.support': '看到你的成長讓我深感欣慰！你正在建立真正的友誼，並在學術上展現自己的能力。這些積極的經歷正在重塑你對自己的認知。你值得這些美好的時刻！🌟📚',
    'caseStudy.thursday.recommendation': '繼續培養與李華的友誼。在其他科目中也嘗試參與課堂討論。記錄每天的小成就。',
    'caseStudy.thursday.pattern': '從友誼的溫暖開始，到學術自信的建立，整天都充滿正能量',
    'caseStudy.thursday.reframe': '你的學術能力一直都在那裡，只是需要合適的環境來展現。友誼給了你安全感，讓你敢於表達自己。',
    'caseStudy.thursday.action': '每天在課堂上至少舉手回答一次問題，即使不確定答案。',
    'caseStudy.thursday.topics.0': '學術自信',
    'caseStudy.thursday.topics.1': '友誼發展',
    'caseStudy.thursday.topics.2': '自我表達',
    'caseStudy.thursday.emotions.0': '溫暖',
    'caseStudy.thursday.emotions.1': '自信',
    'caseStudy.thursday.emotions.2': '被認可',
    'caseStudy.thursday.emotions.3': '滿足',
    'caseStudy.thursday.breakthroughs.0': '在課堂上主動參與並獲得認可',
    'caseStudy.thursday.breakthroughs.1': '與朋友建立了更深的連結',
    'caseStudy.thursday.breakthroughs.2': '開始看到自己的學術價值',
    
    // Friday - Facing Setback
    'caseStudy.friday.summary': '遇到挫折：在體育課被分組時再次被忽視，感到沮喪。但這次選擇與李華談論感受，而非獨自承受。學會了健康的應對方式。',
    'caseStudy.friday.support': '你處理挫折的方式展現了巨大的成長！選擇分享而非隱藏情感，這是情感成熟的標誌。挫折是成長過程的一部分，你已經學會了如何健康地應對它們。💪🤝',
    'caseStudy.friday.recommendation': '與李華討論如何在體育課上更積極地參與。練習自我倡導技巧，學會在適當時候為自己發聲。',
    'caseStudy.friday.pattern': '從挫折的沮喪，到尋求支持，最終獲得理解和安慰',
    'caseStudy.friday.reframe': '被忽視並不代表你不重要。有些人可能只是不知道如何接近你。你的價值不因他人的行為而改變。',
    'caseStudy.friday.action': '下週體育課主動提議加入某個小組，或詢問老師如何更好地參與。',
    'caseStudy.friday.topics.0': '挫折應對',
    'caseStudy.friday.topics.1': '情感支持',
    'caseStudy.friday.topics.2': '自我倡導',
    'caseStudy.friday.emotions.0': '沮喪',
    'caseStudy.friday.emotions.1': '被支持',
    'caseStudy.friday.emotions.2': '理解',
    'caseStudy.friday.emotions.3': '堅強',
    'caseStudy.friday.breakthroughs.0': '選擇尋求朋友支持而非獨自承受',
    'caseStudy.friday.breakthroughs.1': '學會了表達負面情感的健康方式',
    'caseStudy.friday.breakthroughs.2': '意識到挫折不會抹殺之前的進步',
    'caseStudy.friday.concerns.0': '在某些社交場合仍感到被邊緣化',
    
    // Saturday - Integration and Growth
    'caseStudy.saturday.summary': '週末與李華和另外兩位國際學生一起學習，感受到真正的歸屬感。反思這週的經歷，意識到自己的成長和韌性。開始規劃下週的目標。',
    'caseStudy.saturday.support': '這一週的旅程展現了你驚人的韌性和成長能力！從危機到建立友誼，從孤立到歸屬，你已經證明了自己擁有克服困難的力量。你正在成為更強大、更有智慧的自己！🌈✨🎯',
    'caseStudy.saturday.recommendation': '繼續培養這個學習小組。設定下週的具體目標：參與一個課外活動或俱樂部。保持與家人的定期聯繫。',
    'caseStudy.saturday.pattern': '從反思開始，到歸屬感的深化，最終以對未來的積極規劃結束',
    'caseStudy.saturday.reframe': '你的留學之旅不只是學習知識，更是發現自己內在力量的過程。每一次挑戰都讓你變得更堅強。',
    'caseStudy.saturday.action': '寫下這週學到的三個最重要的生活技能，並制定下週的成長計劃。',
    'caseStudy.saturday.topics.0': '自我反思',
    'caseStudy.saturday.topics.1': '歸屬感',
    'caseStudy.saturday.topics.2': '未來規劃',
    'caseStudy.saturday.emotions.0': '反思',
    'caseStudy.saturday.emotions.1': '歸屬',
    'caseStudy.saturday.emotions.2': '自豪',
    'caseStudy.saturday.emotions.3': '樂觀',
    'caseStudy.saturday.breakthroughs.0': '建立了穩固的朋友圈和學習小組',
    'caseStudy.saturday.breakthroughs.1': '發展出健康的應對策略和情感調節技巧',
    'caseStudy.saturday.breakthroughs.2': '從受害者心態轉變為積極的自我倡導者',
    
    // Authentication
    'auth.signIn': '登入',
    'auth.signUp': '註冊',
    'auth.email': '電子郵件',
    'auth.password': '密碼',
    'auth.displayName': '顯示名稱',
    'auth.loading': '載入中...',
    'auth.error': '錯誤',
    'auth.success': '成功',
    'auth.fillAllFields': '請填寫所有欄位',
    'auth.passwordTooShort': '密碼至少需要6個字元',
    'auth.checkEmail': '請檢查您的電子郵件以驗證帳戶',
    'auth.unexpectedError': '發生未預期的錯誤',
    'auth.alreadyHaveAccount': '已有帳戶？點擊登入',
    'auth.dontHaveAccount': '沒有帳戶？點擊註冊',
    'auth.welcome': '歡迎回來！',
    'auth.welcomeNew': '歡迎加入 Rebloom！',
    
    // Common
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '確認',
    'common.back': '返回',
    'common.edit': '編輯',
    'common.delete': '刪除',
    'common.add': '添加',
    'common.remove': '移除',
    'common.loading': '載入中...',
    'common.error': '錯誤',
    'common.success': '成功',
    'common.warning': '警告',
    'common.info': '信息',
  },
  
  'zh-CN': {
    // Navigation
    'nav.home': '聊聊',
    'nav.mood': '心情',
    'nav.explore': '探索',
    'nav.profile': '我的',
    
    // Profile Screen
    'profile.title': '我的',
    'profile.userJoinedDays': '与 Rebloom 相伴 {{days}} 天',
    'profile.logout': '登出',
    'profile.logoutConfirm': '登出确认',
    'profile.logoutMessage': '您确定要登出吗？',
    'profile.cancel': '取消',
    'profile.version': 'Rebloom v{{version}}',
    
    // Profile Sections
    'profile.section.personal': '个人资料',
    'profile.section.subscription': '订阅与付费',
    'profile.section.ai': 'AI 设定',
    'profile.section.notifications': '通知与提醒',
    'profile.section.privacy': '隐私与安全',
    'profile.section.support': '支持与帮助',
    'profile.section.about': '关于',
    
    // Profile Items
    'profile.personalInfo': '个人信息',
    'profile.personalInfo.subtitle': '编辑您的个人资料和偏好',
    'profile.avatar': '头像设置',
    'profile.avatar.subtitle': '更换您的个人头像',
    'profile.subscription': '我的订阅',
    'profile.subscription.subtitle': '管理您的订阅计划',
    'profile.billing': '账单记录',
    'profile.billing.subtitle': '查看付费记录和发票',
    'profile.aiPersonality': 'AI 个性设置',
    'profile.aiPersonality.subtitle': '调整AI伴侣的个性特质和技术特性',
    
    // AI Settings
    'ai.personalizeTitle': '个性化您的AI伴侣',
    'ai.personalizeDescription': '调整AI的个性特质、语音风格和技术特性，打造专属于您的心理健康伴侣。',
    'ai.personality': 'AI个性类型',
    'ai.voiceSettings': '语音设置',
    'ai.voiceType': '语音类型',
    'ai.personalityTraits': '个性特质调节',
    'ai.empathyLevel': '同理心程度',
    'ai.directnessLevel': '直接程度',
    'ai.humorLevel': '幽默感',
    'ai.formalityLevel': '正式程度',
    'ai.modelSettings': 'AI模型设置',
    'ai.languageModel': '语言模型',
    'ai.advancedFeatures': '进阶功能',
    'ai.proactiveSupport': '主动支持',
    'ai.proactiveSupport.description': 'AI会主动关心您的状态并提供支持',
    'ai.smartSuggestions': '智能建议',
    'ai.smartSuggestions.description': '基于对话内容提供个性化建议',
    'ai.learningMode': '学习模式',
    'ai.learningMode.description': 'AI会记住您的偏好并持续改进',
    'ai.voiceEnabled': '语音对话',
    'ai.voiceEnabled.description': '启用语音输入和AI语音回应功能',
    'ai.crisisDetection': '危机检测',
    'ai.crisisDetection.description': '自动检测心理危机并提供适当资源',
    'profile.therapeuticApproach': '治疗方法偏好',
    'profile.therapeuticApproach.subtitle': '选择您偏好的治疗取向',
    'profile.conversationStyle': '对话风格',
    'profile.conversationStyle.subtitle': '设置对话的深度和频率',
    'profile.notifications': '推送通知',
    'profile.notifications.subtitle': '管理通知和提醒设置',
    'profile.moodReminders': '心情记录提醒',
    'profile.moodReminders.subtitle': '设置心情追踪提醒时间',
    'profile.wellnessCheck': '健康检查提醒',
    'profile.wellnessCheck.subtitle': '定期心理健康检查提醒',
    'profile.privacySettings': '隐私设置',
    'profile.privacySettings.subtitle': '控制数据分享和存储',
    'profile.dataExport': '数据导出',
    'profile.dataExport.subtitle': '下载您的对话记录',
    'profile.emergencyContacts': '紧急联络人',
    'profile.emergencyContacts.subtitle': '设置紧急情况联络人',
    'profile.crisisResources': '危机资源',
    'profile.crisisResources.subtitle': '紧急心理健康资源',
    'profile.helpCenter': '帮助中心',
    'profile.helpCenter.subtitle': '常见问题和使用指南',
    'profile.contactSupport': '联络客服',
    'profile.contactSupport.subtitle': '获得技术支持和帮助',
    'profile.feedback': '意见反馈',
    'profile.feedback.subtitle': '帮助我们改进应用',
    'profile.about': '关于 Rebloom',
    'profile.about.subtitle': '应用版本和信息',
    'profile.terms': '服务条款',
    'profile.terms.subtitle': '使用条款和政策',
    'profile.privacyPolicy': '隐私政策',
    'profile.privacyPolicy.subtitle': '了解我们如何保护您的隐私',
    'profile.languageSettings': '语言设置',
    'profile.languageSettings.subtitle': '选择应用显示语言',
    
    // Language Settings
    'language.title': '语言设置',
    'language.select': '选择语言',
    'language.zh-TW': '繁體中文',
    'language.zh-CN': '简体中文',
    'language.ja': '日本語',
    'language.en': 'English',
    'language.save': '保存',
    'language.saveSuccess': '语言设置已保存',
    
    // Home Screen / Chat
    'home.greeting': '嗨！👋\n\n我是 Ash，您的AI心理健康伴侣。我在这里倾听、理解，并帮助您处理心中的想法。\n\n您今天感觉如何？',
    'home.aiResponses.1': '我听到了，我希望您知道您的感受完全有效。您能告诉我更多关于您心中想法的事吗？',
    'home.aiResponses.2': '谢谢您与我分享这些。敞开心扉谈论这些感受需要勇气。您经历这种感觉多久了？',
    'home.aiResponses.3': '我在这里倾听并支持您度过这个困难时期。现在什么对您最有帮助？',
    'home.aiResponses.4': '这听起来真的很有挑战性。您并不孤单，很高兴您寻求支持。',
    'home.aiResponses.5': '我很感谢您信任我。让我们一起解决这个问题。您认为现在什么能让您感觉好一点？',
    
    // Mood Screen
    'mood.title': '心情日记',
    'mood.subtitle': '追踪您的情感旅程',
    'mood.thisWeek': '本周',
    'mood.averageMood': '平均心情',
    'mood.daysTracked': '已追踪天数',
    'mood.insights': '洞察',
    'mood.moodThisWeek': '本周心情',
    'mood.weeklyPatterns': '每周模式',
    'mood.moodImproves': '您的心情在周末会改善',
    'mood.highConfidence': '高置信度',
    'mood.weekendPattern': '您在周六和周日往往感觉更积极。这表明休息和放松对您的健康很重要。',
    'mood.7days': '7天',
    'mood.30days': '30天',
    'mood.3months': '3个月',
    'mood.low': '低',
    'mood.neutral': '中性',
    'mood.high': '高',
    'mood.goodDay': '好日子',
    'mood.toughDay': '艰难的一天',
    'mood.todaysInsights': '今日洞察',
    'mood.insightsFor': '{{date}}的洞察',
    'mood.noConversations': '这一天没有对话',
    'mood.noConversationsText': '选择有对话的日期来查看您的每日洞察和心理支持。',
    'mood.startConversation': '开始对话',
    
    // Daily Insight Card
    'insight.sessions': '次对话',
    'insight.todaysAffirmation': '今日肯定',
    'insight.tomorrowsFocus': '明日重点',
    'insight.emotionalJourney': '情感历程',
    'insight.positiveReframe': '正向重构',
    'insight.actionStep': '行动步骤',
    'insight.conversationAnalysis': '对话分析',
    'insight.messagesShared': '您今天分享了 {{count}} 条消息',
    'insight.emotionalFlow': '情感流动',
    'insight.breakthroughs': '✨ 突破',
    'insight.areasToWatch': '⚠️ 需要关注的地方',
    'insight.saveInsight': '保存洞察',
    'insight.shareProgress': '分享进度',
    
    // Explore/Progress Screen
    'explore.title': '您的进度',
    'explore.thisWeek': '本周',
    'explore.averageMood': '平均心情',
    'explore.daysTracked': '已追踪天数',
    'explore.insights': '洞察',
    'explore.weeklyPatterns': '每周模式',
    'explore.yourGoals': '您的目标',
    'explore.dailyMoodCheckins': '每日心情记录',
    'explore.mindfulnessPractice': '正念练习',
    'explore.daysProgress': '{{current}}/{{total}} 天',
    'explore.moodTrackingSuccess': '您成功地每天追踪心情一整周！🎉',
    'explore.mindfulnessProgress': '继续努力！您正在建立一个很好的习惯。',
    'explore.7days': '7天',
    'explore.30days': '30天',
    'explore.3months': '3个月',
    
    // Weekly Insights
    'weeklyInsight.moodImproves': '您的心情在周末会改善',
    'weeklyInsight.moodImprovesDesc': '您在周六和周日往往感觉更积极。这表明休息和放松对您的健康很重要。',
    'weeklyInsight.consistentImprovement': '本周持续改善',
    'weeklyInsight.consistentImprovementDesc': '您的整体心情在过去7天中呈上升趋势。继续保持！',
    'weeklyInsight.checkinsCompleted': '完成7天记录',
    'weeklyInsight.checkinsCompletedDesc': '恭喜！您连续一周都追踪了心情。这种自我觉察是心理健康旅程中的关键步骤。',
    'weeklyInsight.veryHighConfidence': '极高置信度',
    'weeklyInsight.highConfidence': '高置信度',
    'weeklyInsight.mediumConfidence': '中等置信度',
    'weeklyInsight.lowConfidence': '低置信度',
    
    // Daily Insight Examples
    'insightExample.1.summary': '今天展现了非凡的情感韧性。尽管面临挑战，您保持了积极的态度并主动寻求解决方案。',
    'insightExample.1.support': '您比自己想象的更强大。您今天面对的每一个挑战都证明了您惊人的韧性。您有能力克服生活中的任何困难。💪✨',
    'insightExample.1.recommendation': '继续练习今天有效的接地技巧。考虑在睡前记录您的成就。',
    'insightExample.1.pattern': '从焦虑开始，经历决心，最终以平静的信心结束',
    'insightExample.1.reframe': '感觉像是障碍的事物实际上是成长的机会。您将挑战转化为垫脚石。',
    'insightExample.1.action': '明天早上，提醒自己：「我有能力处理任何困难。」',
    'insightExample.1.topics.0': '韧性',
    'insightExample.1.topics.1': '解决问题',
    'insightExample.1.topics.2': '自我关怀',
    'insightExample.1.emotions.0': '焦虑',
    'insightExample.1.emotions.1': '坚定',
    'insightExample.1.emotions.2': '自信',
    'insightExample.1.emotions.3': '感恩',
    'insightExample.1.breakthroughs.0': '将焦虑视为信息，而非指令',
    'insightExample.1.breakthroughs.1': '在压力时刻成功使用呼吸技巧',
    'insightExample.1.breakthroughs.2': '在困难对话中清楚表达需求',
    
    'insightExample.2.summary': '情绪复杂的一天，但您通过寻求帮助和建设性地处理情感展现了惊人的自我觉察。',
    'insightExample.2.support': '您愿意表现脆弱并寻求支持展现了巨大的勇气。您被爱着、被重视着，值得拥有所有美好的事物。🌟❤️',
    'insightExample.2.recommendation': '练习我们讨论的自我照顾例行公事。记住要像对待亲爱的朋友一样善待自己。',
    'insightExample.2.pattern': '一整天在悲伤和希望之间波动',
    'insightExample.2.reframe': '您的情感起伏是您人性和深度的体现。这不是弱点——这是真实的生活。',
    'insightExample.2.action': '创建一个「善待自己」清单，列出5种您可以对自己表现同情的具体方式。',
    'insightExample.2.topics.0': '自我觉察',
    'insightExample.2.topics.1': '情感处理',
    'insightExample.2.topics.2': '寻求支持',
    'insightExample.2.emotions.0': '忧郁',
    'insightExample.2.emotions.1': '不知所措',
    'insightExample.2.emotions.2': '充满希望',
    'insightExample.2.emotions.3': '平静',
    'insightExample.2.breakthroughs.0': '无评判地识别触发因素',
    'insightExample.2.breakthroughs.1': '感到不知所措时寻求帮助',
    'insightExample.2.breakthroughs.2': '在困难情绪中练习正念呼吸',
    'insightExample.2.concerns.0': '早上自我批评的内心对话',
    'insightExample.2.concerns.1': '倾向于贬低成就',
    
    'insightExample.3.summary': '情感平衡和生产力的绝佳一天。您展现了强大的情商和自我照顾实践。',
    'insightExample.3.support': '您是光明和力量的灯塔。今天您向世界——也向自己——展示了您是多么有能力和美好。继续发光！✨🌈',
    'insightExample.3.recommendation': '通过保持今天有效的例行公事来延续今天的成功。考虑与他人分享您的正能量。',
    'insightExample.3.pattern': '稳定的正能量，伴随着真正的快乐和满足时刻',
    'insightExample.3.reframe': '您通过自己的选择和态度创造了美好的一天。当您信任自己时，这就是您的自然状态。',
    'insightExample.3.action': '写下今天特别的地方，这样您就可以再次创造这些条件。',
    'insightExample.3.topics.0': '平衡',
    'insightExample.3.topics.1': '生产力',
    'insightExample.3.topics.2': '快乐',
    'insightExample.3.emotions.0': '充满活力',
    'insightExample.3.emotions.1': '满足',
    'insightExample.3.emotions.2': '快乐',
    'insightExample.3.breakthroughs.0': '尽管面临意外挑战仍保持积极心态',
    'insightExample.3.breakthroughs.1': '成功平衡工作与自我照顾',
    'insightExample.3.breakthroughs.2': '与所爱的人有意义地连结',
    
    // Case Study: Chinese International Student (Monday-Saturday)
    'caseStudy.student.name': '小明 (化名)',
    'caseStudy.student.profile': '高二中国留学生，16岁，在美国求学3个月',
    
    // Monday - Crisis Day
    'caseStudy.monday.summary': '今天经历了严重的情感危机。在学校食堂被同学嘲笑英语发音，感到深度羞耻和孤立。语言障碍造成的挫败感达到顶峰。',
    'caseStudy.monday.support': '你的感受完全可以理解，小明。适应新文化和语言是极其困难的过程，你已经展现了巨大的勇气。每一个在异国他乡求学的人都会经历这样的挑战。你并不孤单，这些困难是暂时的。💪🌟',
    'caseStudy.monday.recommendation': '明天尝试与学校的国际学生顾问预约谈话。今晚练习深呼吸技巧，写下三件你今天做得好的事情，无论多小。',
    'caseStudy.monday.pattern': '从早上的紧张不安，到中午的羞耻感爆发，晚上陷入深度自我怀疑',
    'caseStudy.monday.reframe': '被嘲笑反映的是他人的无知，而不是你的价值。你的勇气在于每天都在尝试用第二语言沟通，这是值得赞赏的成就。',
    'caseStudy.monday.action': '明天上学前，对镜子说：「我正在学习，每一次尝试都让我更强大。」',
    'caseStudy.monday.topics.0': '语言障碍',
    'caseStudy.monday.topics.1': '校园霸凌',
    'caseStudy.monday.topics.2': '文化适应',
    'caseStudy.monday.emotions.0': '紧张',
    'caseStudy.monday.emotions.1': '羞耻',
    'caseStudy.monday.emotions.2': '孤立',
    'caseStudy.monday.emotions.3': '绝望',
    'caseStudy.monday.breakthroughs.0': '勇敢地向治疗师分享了真实感受',
    'caseStudy.monday.breakthroughs.1': '认识到语言学习需要时间和耐心',
    'caseStudy.monday.concerns.0': '严重的自我价值感低落',
    'caseStudy.monday.concerns.1': '社交回避行为加剧',
    
    // Tuesday - Seeking Help
    'caseStudy.tuesday.summary': '按照建议与国际学生顾问会面。虽然仍感焦虑，但开始寻求学校资源的帮助。第一次感受到被理解和支持。',
    'caseStudy.tuesday.support': '你迈出了最重要的一步！寻求帮助需要巨大的勇气，这显示了你的智慧和成熟。你正在建立支持网络，这是康复过程中的关键步骤。继续相信自己！🌈✨',
    'caseStudy.tuesday.recommendation': '参加学校的英语会话小组。与顾问讨论的应对策略要持续练习。今晚给家人打电话，分享你的感受。',
    'caseStudy.tuesday.pattern': '早上带着忐忑不安的心情，中午感到被理解，晚上出现希望的曙光',
    'caseStudy.tuesday.reframe': '寻求帮助不是软弱的表现，而是智慧和自我关爱的体现。你正在积极地为自己的福祉负责。',
    'caseStudy.tuesday.action': '每天至少与一个人进行英语对话，即使只是简单的问候。',
    'caseStudy.tuesday.topics.0': '寻求帮助',
    'caseStudy.tuesday.topics.1': '建立支持系统',
    'caseStudy.tuesday.topics.2': '自我倡导',
    'caseStudy.tuesday.emotions.0': '忐忑',
    'caseStudy.tuesday.emotions.1': '被理解',
    'caseStudy.tuesday.emotions.2': '希望',
    'caseStudy.tuesday.emotions.3': '感激',
    'caseStudy.tuesday.breakthroughs.0': '成功与学校顾问建立联系',
    'caseStudy.tuesday.breakthroughs.1': '学会了三个应对焦虑的技巧',
    'caseStudy.tuesday.breakthroughs.2': '意识到自己并非唯一面临这些挑战的学生',
    
    // Wednesday - Small Victory
    'caseStudy.wednesday.summary': '参加了英语会话小组，虽然紧张但成功完成了自我介绍。遇到了另一位亚裔同学，感到不再那么孤单。',
    'caseStudy.wednesday.support': '这是一个重大的胜利！你克服了恐惧，勇敢地参与了小组活动。找到同伴是治愈过程中的重要里程碑。你的勇气正在为你打开新的机会之门。🎉💝',
    'caseStudy.wednesday.recommendation': '与新认识的同学保持联系，考虑一起学习或用餐。继续参加会话小组，逐渐建立信心。',
    'caseStudy.wednesday.pattern': '初始紧张，逐渐放松，最终感到归属感和连结',
    'caseStudy.wednesday.reframe': '你的紧张是正常的，但你选择了行动而非回避。这种勇气将成为你未来成功的基石。',
    'caseStudy.wednesday.action': '明天主动向新朋友打招呼，提议一起吃午餐。',
    'caseStudy.wednesday.topics.0': '社交突破',
    'caseStudy.wednesday.topics.1': '建立友谊',
    'caseStudy.wednesday.topics.2': '克服恐惧',
    'caseStudy.wednesday.emotions.0': '紧张',
    'caseStudy.wednesday.emotions.1': '勇敢',
    'caseStudy.wednesday.emotions.2': '连结',
    'caseStudy.wednesday.emotions.3': '希望',
    'caseStudy.wednesday.breakthroughs.0': '成功在小组中自我介绍',
    'caseStudy.wednesday.breakthroughs.1': '建立了第一个潜在友谊',
    'caseStudy.wednesday.breakthroughs.2': '发现其他学生也有类似困扰',
    
    // Thursday - Building Confidence
    'caseStudy.thursday.summary': '与新朋友李华一起吃午餐，分享了彼此的留学经历。在数学课上主动回答问题，获得老师赞赏。自信心开始恢复。',
    'caseStudy.thursday.support': '看到你的成长让我深感欣慰！你正在建立真正的友谊，并在学术上展现自己的能力。这些积极的经历正在重塑你对自己的认知。你值得这些美好的时刻！🌟📚',
    'caseStudy.thursday.recommendation': '继续培养与李华的友谊。在其他科目中也尝试参与课堂讨论。记录每天的小成就。',
    'caseStudy.thursday.pattern': '从友谊的温暖开始，到学术自信的建立，整天都充满正能量',
    'caseStudy.thursday.reframe': '你的学术能力一直都在那里，只是需要合适的环境来展现。友谊给了你安全感，让你敢于表达自己。',
    'caseStudy.thursday.action': '每天在课堂上至少举手回答一次问题，即使不确定答案。',
    'caseStudy.thursday.topics.0': '学术自信',
    'caseStudy.thursday.topics.1': '友谊发展',
    'caseStudy.thursday.topics.2': '自我表达',
    'caseStudy.thursday.emotions.0': '温暖',
    'caseStudy.thursday.emotions.1': '自信',
    'caseStudy.thursday.emotions.2': '被认可',
    'caseStudy.thursday.emotions.3': '满足',
    'caseStudy.thursday.breakthroughs.0': '在课堂上主动参与并获得认可',
    'caseStudy.thursday.breakthroughs.1': '与朋友建立了更深的连结',
    'caseStudy.thursday.breakthroughs.2': '开始看到自己的学术价值',
    
    // Friday - Facing Setback
    'caseStudy.friday.summary': '遇到挫折：在体育课被分组时再次被忽视，感到沮丧。但这次选择与李华谈论感受，而非独自承受。学会了健康的应对方式。',
    'caseStudy.friday.support': '你处理挫折的方式展现了巨大的成长！选择分享而非隐藏情感，这是情感成熟的标志。挫折是成长过程的一部分，你已经学会了如何健康地应对它们。💪🤝',
    'caseStudy.friday.recommendation': '与李华讨论如何在体育课上更积极地参与。练习自我倡导技巧，学会在适当时候为自己发声。',
    'caseStudy.friday.pattern': '从挫折的沮丧，到寻求支持，最终获得理解和安慰',
    'caseStudy.friday.reframe': '被忽视并不代表你不重要。有些人可能只是不知道如何接近你。你的价值不因他人的行为而改变。',
    'caseStudy.friday.action': '下周体育课主动提议加入某个小组，或询问老师如何更好地参与。',
    'caseStudy.friday.topics.0': '挫折应对',
    'caseStudy.friday.topics.1': '情感支持',
    'caseStudy.friday.topics.2': '自我倡导',
    'caseStudy.friday.emotions.0': '沮丧',
    'caseStudy.friday.emotions.1': '被支持',
    'caseStudy.friday.emotions.2': '理解',
    'caseStudy.friday.emotions.3': '坚强',
    'caseStudy.friday.breakthroughs.0': '选择寻求朋友支持而非独自承受',
    'caseStudy.friday.breakthroughs.1': '学会了表达负面情感的健康方式',
    'caseStudy.friday.breakthroughs.2': '意识到挫折不会抹杀之前的进步',
    'caseStudy.friday.concerns.0': '在某些社交场合仍感到被边缘化',
    
    // Saturday - Integration and Growth
    'caseStudy.saturday.summary': '周末与李华和另外两位国际学生一起学习，感受到真正的归属感。反思这周的经历，意识到自己的成长和韧性。开始规划下周的目标。',
    'caseStudy.saturday.support': '这一周的旅程展现了你惊人的韧性和成长能力！从危机到建立友谊，从孤立到归属，你已经证明了自己拥有克服困难的力量。你正在成为更强大、更有智慧的自己！🌈✨🎯',
    'caseStudy.saturday.recommendation': '继续培养这个学习小组。设定下周的具体目标：参与一个课外活动或俱乐部。保持与家人的定期联系。',
    'caseStudy.saturday.pattern': '从反思开始，到归属感的深化，最终以对未来的积极规划结束',
    'caseStudy.saturday.reframe': '你的留学之旅不只是学习知识，更是发现自己内在力量的过程。每一次挑战都让你变得更坚强。',
    'caseStudy.saturday.action': '写下这周学到的三个最重要的生活技能，并制定下周的成长计划。',
    'caseStudy.saturday.topics.0': '自我反思',
    'caseStudy.saturday.topics.1': '归属感',
    'caseStudy.saturday.topics.2': '未来规划',
    'caseStudy.saturday.emotions.0': '反思',
    'caseStudy.saturday.emotions.1': '归属',
    'caseStudy.saturday.emotions.2': '自豪',
    'caseStudy.saturday.emotions.3': '乐观',
    'caseStudy.saturday.breakthroughs.0': '建立了稳固的朋友圈和学习小组',
    'caseStudy.saturday.breakthroughs.1': '发展出健康的应对策略和情感调节技巧',
    'caseStudy.saturday.breakthroughs.2': '从受害者心态转变为积极的自我倡导者',
    
    // Authentication
    'auth.signIn': '登录',
    'auth.signUp': '注册',
    'auth.email': '电子邮件',
    'auth.password': '密码',
    'auth.displayName': '显示名称',
    'auth.loading': '加载中...',
    'auth.error': '错误',
    'auth.success': '成功',
    'auth.fillAllFields': '请填写所有字段',
    'auth.passwordTooShort': '密码至少需要6个字符',
    'auth.checkEmail': '请检查您的电子邮件以验证账户',
    'auth.unexpectedError': '发生未预期的错误',
    'auth.alreadyHaveAccount': '已有账户？点击登录',
    'auth.dontHaveAccount': '没有账户？点击注册',
    'auth.welcome': '欢迎回来！',
    'auth.welcomeNew': '欢迎加入 Rebloom！',
    
    // Common
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.back': '返回',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.add': '添加',
    'common.remove': '移除',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.warning': '警告',
    'common.info': '信息',
  },
  
  'ja': {
    // Navigation
    'nav.home': 'ホーム',
    'nav.mood': '気分',
    'nav.explore': '探索',
    'nav.profile': 'マイページ',
    
    // Profile Screen
    'profile.title': 'マイページ',
    'profile.userJoinedDays': 'Rebloom と共に {{days}} 日',
    'profile.logout': 'ログアウト',
    'profile.logoutConfirm': 'ログアウト確認',
    'profile.logoutMessage': 'ログアウトしてもよろしいですか？',
    'profile.cancel': 'キャンセル',
    'profile.version': 'Rebloom v{{version}}',
    
    // Profile Sections
    'profile.section.personal': '個人情報',
    'profile.section.subscription': 'サブスクリプション',
    'profile.section.ai': 'AI 設定',
    'profile.section.notifications': '通知設定',
    'profile.section.privacy': 'プライバシー',
    'profile.section.support': 'サポート',
    'profile.section.about': 'アプリについて',
    
    // Profile Items
    'profile.personalInfo': '個人情報',
    'profile.personalInfo.subtitle': 'プロフィールと設定を編集',
    'profile.avatar': 'アバター設定',
    'profile.avatar.subtitle': 'プロフィール画像を変更',
    'profile.subscription': 'サブスクリプション',
    'profile.subscription.subtitle': '料金プランを管理',
    'profile.billing': '請求履歴',
    'profile.billing.subtitle': '支払い記録と請求書を確認',
    'profile.aiPersonality': 'AI パーソナリティ',
    'profile.aiPersonality.subtitle': 'AIの個性特性と技術特性を調整',
    
    // AI Settings
    'ai.personalizeTitle': 'AIパートナーをカスタマイズ',
    'ai.personalizeDescription': 'AIの個性特性、音声スタイル、技術特性を調整して、あなた専用のメンタルヘルスパートナーを作りましょう。',
    'ai.personality': 'AI個性タイプ',
    'ai.voiceSettings': '音声設定',
    'ai.voiceType': '音声タイプ',
    'ai.personalityTraits': '個性特性調整',
    'ai.empathyLevel': '共感レベル',
    'ai.directnessLevel': '直接性レベル',
    'ai.humorLevel': 'ユーモア',
    'ai.formalityLevel': 'フォーマル度',
    'ai.modelSettings': 'AIモデル設定',
    'ai.languageModel': '言語モデル',
    'ai.advancedFeatures': '高度な機能',
    'ai.proactiveSupport': 'プロアクティブサポート',
    'ai.proactiveSupport.description': 'AIがあなたの状態を積極的に気にかけ、サポートを提供します',
    'ai.smartSuggestions': 'スマート提案',
    'ai.smartSuggestions.description': '会話内容に基づいてパーソナライズされた提案を提供',
    'ai.learningMode': '学習モード',
    'ai.learningMode.description': 'AIがあなたの好みを覚えて継続的に改善します',
    'ai.voiceEnabled': '音声会話',
    'ai.voiceEnabled.description': '音声入力とAI音声応答機能を有効にします',
    'ai.crisisDetection': 'クライシス検出',
    'ai.crisisDetection.description': '心理的危機を自動検出し、適切なリソースを提供',
    'profile.therapeuticApproach': '治療アプローチ',
    'profile.therapeuticApproach.subtitle': '好みの治療方法を選択',
    'profile.conversationStyle': '会話スタイル',
    'profile.conversationStyle.subtitle': '会話の深度と頻度を設定',
    'profile.notifications': 'プッシュ通知',
    'profile.notifications.subtitle': '通知とリマインダーを管理',
    'profile.moodReminders': '気分記録リマインダー',
    'profile.moodReminders.subtitle': '気分追跡の通知時間を設定',
    'profile.wellnessCheck': 'ウェルネスチェック',
    'profile.wellnessCheck.subtitle': '定期的なメンタルヘルスチェック',
    'profile.privacySettings': 'プライバシー設定',
    'profile.privacySettings.subtitle': 'データ共有と保存を制御',
    'profile.dataExport': 'データエクスポート',
    'profile.dataExport.subtitle': '会話記録をダウンロード',
    'profile.emergencyContacts': '緊急連絡先',
    'profile.emergencyContacts.subtitle': '緊急時の連絡先を設定',
    'profile.crisisResources': 'クライシスリソース',
    'profile.crisisResources.subtitle': '緊急メンタルヘルスリソース',
    'profile.helpCenter': 'ヘルプセンター',
    'profile.helpCenter.subtitle': 'よくある質問と使用ガイド',
    'profile.contactSupport': 'サポートに連絡',
    'profile.contactSupport.subtitle': '技術サポートとヘルプを取得',
    'profile.feedback': 'フィードバック',
    'profile.feedback.subtitle': 'アプリの改善にご協力ください',
    'profile.about': 'Rebloom について',
    'profile.about.subtitle': 'アプリのバージョンと情報',
    'profile.terms': '利用規約',
    'profile.terms.subtitle': '利用条件とポリシー',
    'profile.privacyPolicy': 'プライバシーポリシー',
    'profile.privacyPolicy.subtitle': 'プライバシー保護について',
    'profile.languageSettings': '言語設定',
    'profile.languageSettings.subtitle': 'アプリの表示言語を選択',
    
    // Language Settings
    'language.title': '言語設定',
    'language.select': '言語を選択',
    'language.zh-TW': '繁體中文',
    'language.zh-CN': '简体中文',
    'language.ja': '日本語',
    'language.en': 'English',
    'language.save': '保存',
    'language.saveSuccess': '言語設定が保存されました',
    
    // Home Screen / Chat
    'home.greeting': 'こんにちは！👋\n\n私はAsh、あなたのAIメンタルヘルスコンパニオンです。お話を聞き、理解し、心の中にあることを整理するお手伝いをします。\n\n今日の気分はいかがですか？',
    'home.aiResponses.1': 'お聞きしました。あなたの感情は完全に正当なものだということを知ってください。心の中にあることについて、もう少し教えていただけますか？',
    'home.aiResponses.2': 'お話しいただき、ありがとうございます。このような感情について心を開くには勇気が必要ですね。この感覚をどのくらい経験されていますか？',
    'home.aiResponses.3': 'この困難な時期を乗り越えるために、お話を聞き、サポートいたします。今、何が一番お役に立てるでしょうか？',
    'home.aiResponses.4': 'それは本当に大変そうですね。あなたは一人ではありません。サポートを求めてくださって嬉しく思います。',
    'home.aiResponses.5': '信頼してお話しいただき、感謝しています。一緒に取り組みましょう。今、少しでも気分が良くなるために何ができると思いますか？',
    
    // Mood Screen
    'mood.title': '気分日記',
    'mood.subtitle': '感情の旅路を記録',
    'mood.thisWeek': '今週',
    'mood.averageMood': '平均気分',
    'mood.daysTracked': '記録日数',
    'mood.insights': 'インサイト',
    'mood.moodThisWeek': '今週の気分',
    'mood.weeklyPatterns': '週間パターン',
    'mood.moodImproves': '週末に気分が改善されます',
    'mood.highConfidence': '高い信頼度',
    'mood.weekendPattern': '土曜日と日曜日により積極的な気持ちになる傾向があります。これは、休息とリラクゼーションがあなたの健康にとって重要であることを示しています。',
    'mood.7days': '7日間',
    'mood.30days': '30日間',
    'mood.3months': '3ヶ月',
    'mood.low': '低',
    'mood.neutral': '普通',
    'mood.high': '高',
    'mood.goodDay': '良い日',
    'mood.toughDay': '辛い日',
    'mood.todaysInsights': '今日のインサイト',
    'mood.insightsFor': '{{date}}のインサイト',
    'mood.noConversations': 'この日は会話がありません',
    'mood.noConversationsText': '会話のある日を選択して、毎日のインサイトと心理的サポートを確認してください。',
    'mood.startConversation': '会話を開始',
    
    // Daily Insight Card
    'insight.sessions': 'セッション',
    'insight.todaysAffirmation': '今日のアファメーション',
    'insight.tomorrowsFocus': '明日のフォーカス',
    'insight.emotionalJourney': '感情の旅',
    'insight.positiveReframe': 'ポジティブリフレーム',
    'insight.actionStep': 'アクションステップ',
    'insight.conversationAnalysis': '会話分析',
    'insight.messagesShared': '今日 {{count}} メッセージを共有しました',
    'insight.emotionalFlow': '感情の流れ',
    'insight.breakthroughs': '✨ ブレークスルー',
    'insight.areasToWatch': '⚠️ 注意すべき領域',
    'insight.saveInsight': 'インサイトを保存',
    'insight.shareProgress': '進捗を共有',
    
    // Explore/Progress Screen
    'explore.title': 'あなたの進捗',
    'explore.thisWeek': '今週',
    'explore.averageMood': '平均気分',
    'explore.daysTracked': '記録日数',
    'explore.insights': 'インサイト',
    'explore.weeklyPatterns': '週間パターン',
    'explore.yourGoals': 'あなたの目標',
    'explore.dailyMoodCheckins': '毎日の気分チェック',
    'explore.mindfulnessPractice': 'マインドフルネス練習',
    'explore.daysProgress': '{{current}}/{{total}} 日',
    'explore.moodTrackingSuccess': '一週間毎日気分を記録することに成功しました！🎉',
    'explore.mindfulnessProgress': '頑張って！素晴らしい習慣を築いています。',
    'explore.7days': '7日間',
    'explore.30days': '30日間',
    'explore.3months': '3ヶ月',
    
    // Weekly Insights
    'weeklyInsight.moodImproves': '週末に気分が改善されます',
    'weeklyInsight.moodImprovesDesc': '土曜日と日曜日により積極的な気持ちになる傾向があります。これは、休息とリラクゼーションがあなたの健康にとって重要であることを示しています。',
    'weeklyInsight.consistentImprovement': '今週の継続的な改善',
    'weeklyInsight.consistentImprovementDesc': '過去7日間で全体的な気分が上向きになっています。この調子で続けてください！',
    'weeklyInsight.checkinsCompleted': '7日間のチェックイン完了',
    'weeklyInsight.checkinsCompletedDesc': 'おめでとうございます！一週間連続で気分を記録しました。この自己認識は、メンタルヘルスの旅における重要なステップです。',
    'weeklyInsight.veryHighConfidence': '非常に高い信頼度',
    'weeklyInsight.highConfidence': '高い信頼度',
    'weeklyInsight.mediumConfidence': '中程度の信頼度',
    'weeklyInsight.lowConfidence': '低い信頼度',
    
    // Daily Insight Examples
    'insightExample.1.summary': '今日は驚くべき感情的回復力を示しました。困難に直面しても、前向きな見通しを保ち、積極的に解決策を求めました。',
    'insightExample.1.support': 'あなたは自分が思っているより強いです。今日直面したすべての困難は、あなたの驚くべき回復力の証拠です。人生が与えるどんなことでも乗り越える力があります。💪✨',
    'insightExample.1.recommendation': '今日効果的だったグラウンディング技術を続けて練習してください。就寝前に成果を記録することを検討してください。',
    'insightExample.1.pattern': '不安から始まり、決意を経て、最終的に穏やかな自信で終わりました',
    'insightExample.1.reframe': '障害のように感じたものは、実際には成長の機会でした。あなたは困難を踏み台に変えました。',
    'insightExample.1.action': '明日の朝、自分に思い出させてください：「私はどんな困難でも対処できる」',
    'insightExample.1.topics.0': '回復力',
    'insightExample.1.topics.1': '問題解決',
    'insightExample.1.topics.2': 'セルフコンパッション',
    'insightExample.1.emotions.0': '不安',
    'insightExample.1.emotions.1': '決意',
    'insightExample.1.emotions.2': '自信',
    'insightExample.1.emotions.3': '感謝',
    'insightExample.1.breakthroughs.0': '不安を指示ではなく情報として認識',
    'insightExample.1.breakthroughs.1': 'ストレスの瞬間に呼吸法を成功的に使用',
    'insightExample.1.breakthroughs.2': '困難な会話で明確にニーズを表現',
    
    'insightExample.2.summary': '複雑な感情の日でしたが、助けを求め、建設的に感情を処理することで驚くべき自己認識を示しました。',
    'insightExample.2.support': '脆弱性を示し、サポートを求める意欲は大きな勇気を示しています。あなたは愛され、価値があり、すべての良いことを受ける価値があります。🌟❤️',
    'insightExample.2.recommendation': '私たちが話し合ったセルフケアルーチンを実践してください。大切な友人に接するように自分に優しくすることを忘れないでください。',
    'insightExample.2.pattern': '一日中悲しみと希望の間を揺れ動きました',
    'insightExample.2.reframe': 'あなたの感情の起伏は、あなたの人間性と深さの表れです。これは弱さではありません—これは本物の生活です。',
    'insightExample.2.action': '自分に優しくする5つの具体的な方法を書いた「自己への優しさ」リストを作成してください。',
    'insightExample.2.topics.0': '自己認識',
    'insightExample.2.topics.1': '感情処理',
    'insightExample.2.topics.2': 'サポート求め',
    'insightExample.2.emotions.0': '憂鬱',
    'insightExample.2.emotions.1': '圧倒された',
    'insightExample.2.emotions.2': '希望に満ちた',
    'insightExample.2.emotions.3': '平和',
    'insightExample.2.breakthroughs.0': '判断なしにトリガーを特定',
    'insightExample.2.breakthroughs.1': '圧倒されたときに助けを求める',
    'insightExample.2.breakthroughs.2': '困難な感情の中でマインドフル呼吸を実践',
    'insightExample.2.concerns.0': '朝の自己批判的な内なる対話',
    'insightExample.2.concerns.1': '成果を過小評価する傾向',
    
    'insightExample.3.summary': '感情的バランスと生産性の素晴らしい一日。強い感情知能とセルフケア実践を示しました。',
    'insightExample.3.support': 'あなたは光と力の灯台です。今日、あなたは世界に—そして自分自身に—どれほど有能で素晴らしいかを示しました。輝き続けてください！✨🌈',
    'insightExample.3.recommendation': '今日効果的だったルーチンを維持することで今日の成功を築いてください。他の人とあなたの前向きなエネルギーを共有することを検討してください。',
    'insightExample.3.pattern': '真の喜びと満足の瞬間を伴う安定した前向きなエネルギー',
    'insightExample.3.reframe': 'あなたは自分の選択と態度を通して美しい一日を作り出しました。自分を信頼するとき、これがあなたの自然な状態です。',
    'insightExample.3.action': '今日何が特別だったかを書き留めて、これらの条件を再び作り出せるようにしてください。',
    'insightExample.3.topics.0': 'バランス',
    'insightExample.3.topics.1': '生産性',
    'insightExample.3.topics.2': '喜び',
    'insightExample.3.emotions.0': 'エネルギッシュ',
    'insightExample.3.emotions.1': '満足',
    'insightExample.3.emotions.2': '喜び',
    'insightExample.3.breakthroughs.0': '予期しない困難にもかかわらず前向きな考え方を維持',
    'insightExample.3.breakthroughs.1': '仕事とセルフケアのバランスを成功的に取った',
    'insightExample.3.breakthroughs.2': '愛する人々と意味のあるつながりを持った',
    
    // Authentication
    'auth.signIn': 'サインイン',
    'auth.signUp': 'サインアップ',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.displayName': '表示名',
    'auth.loading': '読み込み中...',
    'auth.error': 'エラー',
    'auth.success': '成功',
    'auth.fillAllFields': 'すべてのフィールドを入力してください',
    'auth.passwordTooShort': 'パスワードは6文字以上である必要があります',
    'auth.checkEmail': 'アカウント確認のためメールをご確認ください',
    'auth.unexpectedError': '予期しないエラーが発生しました',
    'auth.alreadyHaveAccount': 'アカウントをお持ちですか？サインインをクリック',
    'auth.dontHaveAccount': 'アカウントをお持ちでない場合は？サインアップをクリック',
    'auth.welcome': 'おかえりなさい！',
    'auth.welcomeNew': 'Rebloom へようこそ！',
    
    // Common
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.back': '戻る',
    'common.edit': '編集',
    'common.delete': '削除',
    'common.add': '追加',
    'common.remove': '削除',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.warning': '警告',
    'common.info': '情報',
  },
  
  'en': {
    // Navigation
    'nav.home': 'Home',
    'nav.mood': 'Mood',
    'nav.explore': 'Explore',
    'nav.profile': 'Profile',
    
    // Profile Screen
    'profile.title': 'Profile',
    'profile.userJoinedDays': '{{days}} days with Rebloom',
    'profile.logout': 'Logout',
    'profile.logoutConfirm': 'Confirm Logout',
    'profile.logoutMessage': 'Are you sure you want to logout?',
    'profile.cancel': 'Cancel',
    'profile.version': 'Rebloom v{{version}}',
    
    // Profile Sections
    'profile.section.personal': 'Personal',
    'profile.section.subscription': 'Subscription',
    'profile.section.ai': 'AI Settings',
    'profile.section.notifications': 'Notifications',
    'profile.section.privacy': 'Privacy & Security',
    'profile.section.support': 'Support & Help',
    'profile.section.about': 'About',
    
    // Profile Items
    'profile.personalInfo': 'Personal Information',
    'profile.personalInfo.subtitle': 'Edit your profile and preferences',
    'profile.avatar': 'Avatar Settings',
    'profile.avatar.subtitle': 'Change your profile picture',
    'profile.subscription': 'My Subscription',
    'profile.subscription.subtitle': 'Manage your subscription plan',
    'profile.billing': 'Billing History',
    'profile.billing.subtitle': 'View payment records and invoices',
    'profile.aiPersonality': 'AI Personality',
    'profile.aiPersonality.subtitle': 'Adjust AI personality traits and technical features',
    
    // AI Settings
    'ai.personalizeTitle': 'Personalize Your AI Companion',
    'ai.personalizeDescription': 'Adjust AI personality traits, voice style, and technical features to create your personalized mental health companion.',
    'ai.personality': 'AI Personality Type',
    'ai.voiceSettings': 'Voice Settings',
    'ai.voiceType': 'Voice Type',
    'ai.personalityTraits': 'Personality Traits',
    'ai.empathyLevel': 'Empathy Level',
    'ai.directnessLevel': 'Directness Level',
    'ai.humorLevel': 'Humor Level',
    'ai.formalityLevel': 'Formality Level',
    'ai.modelSettings': 'AI Model Settings',
    'ai.languageModel': 'Language Model',
    'ai.advancedFeatures': 'Advanced Features',
    'ai.proactiveSupport': 'Proactive Support',
    'ai.proactiveSupport.description': 'AI will proactively check on your wellbeing and offer support',
    'ai.smartSuggestions': 'Smart Suggestions',
    'ai.smartSuggestions.description': 'Provide personalized suggestions based on conversation content',
    'ai.learningMode': 'Learning Mode',
    'ai.learningMode.description': 'AI will remember your preferences and continuously improve',
    'ai.voiceEnabled': 'Voice Conversation',
    'ai.voiceEnabled.description': 'Enable voice input and AI voice response features',
    'ai.crisisDetection': 'Crisis Detection',
    'ai.crisisDetection.description': 'Automatically detect mental health crises and provide appropriate resources',
    'profile.therapeuticApproach': 'Therapeutic Approach',
    'profile.therapeuticApproach.subtitle': 'Choose your preferred therapy methods',
    'profile.conversationStyle': 'Conversation Style',
    'profile.conversationStyle.subtitle': 'Set conversation depth and frequency',
    'profile.notifications': 'Push Notifications',
    'profile.notifications.subtitle': 'Manage notification and reminder settings',
    'profile.moodReminders': 'Mood Reminders',
    'profile.moodReminders.subtitle': 'Set mood tracking reminder times',
    'profile.wellnessCheck': 'Wellness Check',
    'profile.wellnessCheck.subtitle': 'Regular mental health check reminders',
    'profile.privacySettings': 'Privacy Settings',
    'profile.privacySettings.subtitle': 'Control data sharing and storage',
    'profile.dataExport': 'Data Export',
    'profile.dataExport.subtitle': 'Download your conversation records',
    'profile.emergencyContacts': 'Emergency Contacts',
    'profile.emergencyContacts.subtitle': 'Set emergency situation contacts',
    'profile.crisisResources': 'Crisis Resources',
    'profile.crisisResources.subtitle': 'Emergency mental health resources',
    'profile.helpCenter': 'Help Center',
    'profile.helpCenter.subtitle': 'FAQ and usage guides',
    'profile.contactSupport': 'Contact Support',
    'profile.contactSupport.subtitle': 'Get technical support and help',
    'profile.feedback': 'Feedback',
    'profile.feedback.subtitle': 'Help us improve the app',
    'profile.about': 'About Rebloom',
    'profile.about.subtitle': 'App version and information',
    'profile.terms': 'Terms of Service',
    'profile.terms.subtitle': 'Usage terms and policies',
    'profile.privacyPolicy': 'Privacy Policy',
    'profile.privacyPolicy.subtitle': 'Learn how we protect your privacy',
    'profile.languageSettings': 'Language Settings',
    'profile.languageSettings.subtitle': 'Choose app display language',
    
    // Language Settings
    'language.title': 'Language Settings',
    'language.select': 'Select Language',
    'language.zh-TW': '繁體中文',
    'language.zh-CN': '简体中文',
    'language.ja': '日本語',
    'language.en': 'English',
    'language.save': 'Save',
    'language.saveSuccess': 'Language settings saved',
    
    // Home Screen / Chat
    'home.greeting': 'Hi there! 👋\n\nI\'m Ash, your AI companion for mental health support. I\'m here to listen, understand, and help you work through whatever is on your mind.\n\nHow are you feeling today?',
    'home.aiResponses.1': 'I hear you, and I want you to know that what you\'re feeling is completely valid. Can you tell me more about what\'s been on your mind?',
    'home.aiResponses.2': 'Thank you for sharing that with me. It takes courage to open up about these feelings. How long have you been experiencing this?',
    'home.aiResponses.3': 'I\'m here to listen and support you through this. What would be most helpful for you right now?',
    'home.aiResponses.4': 'That sounds really challenging. You\'re not alone in feeling this way, and I\'m glad you\'re reaching out for support.',
    'home.aiResponses.5': 'I appreciate you trusting me with this. Let\'s work through this together. What do you think might help you feel a bit better right now?',
    
    // Mood Screen
    'mood.title': 'Mood Journal',
    'mood.subtitle': 'Track your emotional journey',
    'mood.thisWeek': 'This Week',
    'mood.averageMood': 'Average Mood',
    'mood.daysTracked': 'Days Tracked',
    'mood.insights': 'Insights',
    'mood.moodThisWeek': 'Mood This Week',
    'mood.weeklyPatterns': 'Weekly Patterns',
    'mood.moodImproves': 'Your mood improves on weekends',
    'mood.highConfidence': 'High Confidence',
    'mood.weekendPattern': 'You tend to feel more positive on Saturdays and Sundays. This suggests that rest and relaxation are important for your wellbeing.',
    'mood.7days': '7 days',
    'mood.30days': '30 days',
    'mood.3months': '3 months',
    'mood.low': 'Low',
    'mood.neutral': 'Neutral',
    'mood.high': 'High',
    'mood.goodDay': 'Good Day',
    'mood.toughDay': 'Tough Day',
    'mood.todaysInsights': 'Today\'s Insights',
    'mood.insightsFor': 'Insights for {{date}}',
    'mood.noConversations': 'No conversations on this day',
    'mood.noConversationsText': 'Select a day with conversations to see your daily insights and psychological support.',
    'mood.startConversation': 'Start Conversation',
    
    // Daily Insight Card
    'insight.sessions': 'sessions',
    'insight.todaysAffirmation': 'Today\'s Affirmation',
    'insight.tomorrowsFocus': 'Tomorrow\'s Focus',
    'insight.emotionalJourney': 'Emotional Journey',
    'insight.positiveReframe': 'Positive Reframe',
    'insight.actionStep': 'Action Step',
    'insight.conversationAnalysis': 'Conversation Analysis',
    'insight.messagesShared': 'You shared {{count}} messages today',
    'insight.emotionalFlow': 'Emotional Flow',
    'insight.breakthroughs': '✨ Breakthroughs',
    'insight.areasToWatch': '⚠️ Areas to Watch',
    'insight.saveInsight': 'Save Insight',
    'insight.shareProgress': 'Share Progress',
    
    // Explore/Progress Screen
    'explore.title': 'Your Progress',
    'explore.thisWeek': 'This Week',
    'explore.averageMood': 'Average Mood',
    'explore.daysTracked': 'Days Tracked',
    'explore.insights': 'Insights',
    'explore.weeklyPatterns': 'Weekly Patterns',
    'explore.yourGoals': 'Your Goals',
    'explore.dailyMoodCheckins': 'Daily Mood Check-ins',
    'explore.mindfulnessPractice': 'Mindfulness Practice',
    'explore.daysProgress': '{{current}}/{{total}} days',
    'explore.moodTrackingSuccess': 'You\'ve successfully tracked your mood every day this week! 🎉',
    'explore.mindfulnessProgress': 'Keep going! You\'re building a great habit.',
    'explore.7days': '7 days',
    'explore.30days': '30 days',
    'explore.3months': '3 months',
    
    // Weekly Insights
    'weeklyInsight.moodImproves': 'Your mood improves on weekends',
    'weeklyInsight.moodImprovesDesc': 'You tend to feel more positive on Saturdays and Sundays. This suggests that rest and relaxation are important for your wellbeing.',
    'weeklyInsight.consistentImprovement': 'Consistent improvement this week',
    'weeklyInsight.consistentImprovementDesc': 'Your overall mood has been trending upward over the past 7 days. Keep up the great work!',
    'weeklyInsight.checkinsCompleted': '7 days of check-ins completed',
    'weeklyInsight.checkinsCompletedDesc': 'Congratulations! You\'ve consistently tracked your mood for a full week. This self-awareness is a key step in your mental health journey.',
    'weeklyInsight.veryHighConfidence': 'Very High Confidence',
    'weeklyInsight.highConfidence': 'High Confidence',
    'weeklyInsight.mediumConfidence': 'Medium Confidence',
    'weeklyInsight.lowConfidence': 'Low Confidence',
    
    // Daily Insight Examples
    'insightExample.1.summary': 'Today showed remarkable emotional resilience. Despite facing challenges, you maintained a positive outlook and actively sought solutions.',
    'insightExample.1.support': 'You are stronger than you know. Every challenge you\'ve faced today is proof of your incredible resilience. You have the power to overcome anything life presents to you. 💪✨',
    'insightExample.1.recommendation': 'Continue practicing the grounding techniques that worked well today. Consider journaling your achievements before bed.',
    'insightExample.1.pattern': 'Started anxious, moved through determination, ended with calm confidence',
    'insightExample.1.reframe': 'What felt like obstacles were actually opportunities for growth. You transformed challenges into stepping stones.',
    'insightExample.1.action': 'Tomorrow morning, remind yourself: \'I am capable of handling whatever comes my way.\'',
    'insightExample.1.topics.0': 'Resilience',
    'insightExample.1.topics.1': 'Problem-solving',
    'insightExample.1.topics.2': 'Self-compassion',
    'insightExample.1.emotions.0': 'Anxious',
    'insightExample.1.emotions.1': 'Determined',
    'insightExample.1.emotions.2': 'Confident',
    'insightExample.1.emotions.3': 'Grateful',
    'insightExample.1.breakthroughs.0': 'Recognized anxiety as information, not instruction',
    'insightExample.1.breakthroughs.1': 'Successfully used breathing technique during stressful moment',
    'insightExample.1.breakthroughs.2': 'Expressed needs clearly in difficult conversation',
    
    'insightExample.2.summary': 'A day of mixed emotions, but you showed incredible self-awareness by reaching out and processing your feelings constructively.',
    'insightExample.2.support': 'Your willingness to be vulnerable and seek support shows immense courage. You are loved, valued, and worthy of all the good things coming your way. 🌟❤️',
    'insightExample.2.recommendation': 'Practice the self-care routine we discussed. Remember to be as kind to yourself as you would be to a dear friend.',
    'insightExample.2.pattern': 'Fluctuated between sadness and hope throughout the day',
    'insightExample.2.reframe': 'Your emotional ups and downs are signs of your humanity and depth. This isn\'t weakness—it\'s authentic living.',
    'insightExample.2.action': 'Create a \'kindness to self\' list with 5 specific ways you can show yourself compassion.',
    'insightExample.2.topics.0': 'Self-awareness',
    'insightExample.2.topics.1': 'Emotional processing',
    'insightExample.2.topics.2': 'Support-seeking',
    'insightExample.2.emotions.0': 'Melancholy',
    'insightExample.2.emotions.1': 'Overwhelmed',
    'insightExample.2.emotions.2': 'Hopeful',
    'insightExample.2.emotions.3': 'Peaceful',
    'insightExample.2.breakthroughs.0': 'Identified triggers without self-judgment',
    'insightExample.2.breakthroughs.1': 'Asked for help when feeling overwhelmed',
    'insightExample.2.breakthroughs.2': 'Practiced mindful breathing during difficult emotions',
    'insightExample.2.concerns.0': 'Self-critical inner dialogue in the morning',
    'insightExample.2.concerns.1': 'Tendency to minimize achievements',
    
    'insightExample.3.summary': 'An excellent day of emotional balance and productivity. You demonstrated strong emotional intelligence and self-care practices.',
    'insightExample.3.support': 'You are a beacon of light and strength. Today you showed the world—and yourself—just how capable and wonderful you are. Keep shining! ✨🌈',
    'insightExample.3.recommendation': 'Build on today\'s success by maintaining the routines that served you well. Consider sharing your positive energy with others.',
    'insightExample.3.pattern': 'Steady positive energy with moments of genuine joy and satisfaction',
    'insightExample.3.reframe': 'You\'ve created a beautiful day through your choices and attitude. This is your natural state when you trust yourself.',
    'insightExample.3.action': 'Write down what made today special so you can recreate these conditions again.',
    'insightExample.3.topics.0': 'Balance',
    'insightExample.3.topics.1': 'Productivity',
    'insightExample.3.topics.2': 'Joy',
    'insightExample.3.emotions.0': 'Energized',
    'insightExample.3.emotions.1': 'Content',
    'insightExample.3.emotions.2': 'Joyful',
    'insightExample.3.breakthroughs.0': 'Maintained positive mindset despite unexpected challenges',
    'insightExample.3.breakthroughs.1': 'Successfully balanced work and self-care',
    'insightExample.3.breakthroughs.2': 'Expressed gratitude and appreciation to others',
    
    // Authentication
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.displayName': 'Display Name',
    'auth.loading': 'Loading...',
    'auth.error': 'Error',
    'auth.success': 'Success',
    'auth.fillAllFields': 'Please fill all fields',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.checkEmail': 'Please check your email to verify your account',
    'auth.unexpectedError': 'An unexpected error occurred',
    'auth.alreadyHaveAccount': 'Already have an account? Click to sign in',
    'auth.dontHaveAccount': 'Don\'t have an account? Click to sign up',
    'auth.welcome': 'Welcome back!',
    'auth.welcomeNew': 'Welcome to Rebloom!',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('zh-TW');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage && ['zh-TW', 'zh-CN', 'ja', 'en'].includes(savedLanguage)) {
        setLanguageState(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (newLanguage: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, newLanguage);
      setLanguageState(newLanguage);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const resetLanguage = async () => {
    try {
      await AsyncStorage.removeItem(LANGUAGE_STORAGE_KEY);
      setLanguageState('zh-TW');
    } catch (error) {
      console.error('Error resetting language:', error);
    }
  };

  const t = (key: string, params?: Record<string, string>): string => {
    const translation = (translations[language] as any)?.[key] || (translations['zh-TW'] as any)?.[key] || key;
    
    if (params) {
      return Object.entries(params).reduce(
        (text, [param, value]) => text.replace(`{{${param}}}`, value),
        translation
      );
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, resetLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};