# Prometheus configuration for Rebloom monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rebloom-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Rebloom API monitoring
  - job_name: 'rebloom-api'
    static_configs:
      - targets: ['api:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 30s
    metrics_path: /nginx-status

  # Docker container monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Application-specific metrics
  - job_name: 'rebloom-custom-metrics'
    static_configs:
      - targets: ['api:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    basic_auth:
      username: 'metrics'
      password: 'secure_metrics_password'

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets:
        - 'api:3000'
        - 'redis:6379'
    scrape_interval: 10s
    metrics_path: /health
    params:
      format: ['prometheus']

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.rebloom.app/api/v1/write"
    basic_auth:
      username: "rebloom"
      password: "${PROMETHEUS_REMOTE_WRITE_PASSWORD}"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'rebloom_.*'
        target_label: __name__
        replacement: '${1}'

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true